#!/bin/bash

#/////////////////////////

SD="$(dirname "$(readlink -e "$0")")"
WD="`pwd`"
SCRIPT="$(basename $0)"
SCRIPT_NAME=${SCRIPT%.*}
SCRIPT_EXTENSION=${SCRIPT##*.}
SELF=$SD/$SCRIPT

#/////////////////////////

set -e

#/////////////////////////

MODE=$1

if [[ "$MODE" == "install" ]] ; then
	echo "Installing package"
fi
if [[ "$MODE" == "upgrade" ]] ; then
	echo "Upgrading package"
fi
if [[ "$MODE" == "remove" ]] ; then
	echo "Removing package"
fi
if [[ "$MODE" == "configure" ]] ; then
	echo "Configuring package"
fi

#/////////////////////////

service_exists() {
    local n=$1
    if [[ $(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ') == $n.service ]]; then
        return 0
    else
        return 1
    fi
}

#/////////////////////////

# Unregister service if installed

if service_exists ${assembly.name}; then
	echo "Unregistering service '${assembly.name}'"

	systemctl stop ${assembly.name}
	systemctl disable ${assembly.name}
else
	echo "Service '${assembly.name}' not properly installed. No unregistering needed."
fi

#/////////////////////////

if [ -d "${assembly.installationdir}/" ]; then
	echo "Deleting files ('${assembly.installationdir}')..."
	rm -f -R ${assembly.installationdir}/
fi

#/////////////////////////